#!/usr/bin/env bash

if [ $0 != $BASH_SOURCE ]; then
  script_dir=$(dirname $(readlink -f "${BASH_SOURCE}"))
else
  script_dir=$(dirname $(readlink -f "${0}"))
fi
source "${script_dir}/ikfs-common"

function update_repository() {
  local opwd=$(pwd)
  local chroot_dir="${1}"
  local this_repo_dir=$(readlink -f "${2}")

  mkdir -p "${this_repo_dir}/pool/main"
  mkdir -p "${this_repo_dir}/pool/contrib"
  mkdir -p "${this_repo_dir}/pool/non-free"
  mkdir -p "${this_repo_dir}/dists/${os_codename}/main/binary-${os_cpu_alt_name}"
  mkdir -p "${this_repo_dir}/dists/${os_codename}/contrib/binary-${os_cpu_alt_name}"
  mkdir -p "${this_repo_dir}/dists/${os_codename}/non-free/binary-${os_cpu_alt_name}"
  cd "${this_repo_dir}"
  cp "${chroot_dir}/usr/src/"*.deb "${this_repo_dir}/pool/main/"

  download_extras "${this_repo_dir}"

  apt-ftparchive --arch ${os_cpu_alt_name} packages pool/main | \
    tee ${this_repo_dir}/dists/${os_codename}/main/binary-${os_cpu_alt_name}/Packages | \
    gzip -9 >${this_repo_dir}/dists/${os_codename}/main/binary-${os_cpu_alt_name}/Packages.gz
  apt-ftparchive --arch ${os_cpu_alt_name} packages pool/contrib | \
    tee ${this_repo_dir}/dists/${os_codename}/contrib/binary-${os_cpu_alt_name}/Packages | \
    gzip -9 >${this_repo_dir}/dists/${os_codename}/contrib/binary-${os_cpu_alt_name}/Packages.gz
  apt-ftparchive --arch ${os_cpu_alt_name} packages pool/non-free | \
    tee ${this_repo_dir}/dists/${os_codename}/non-free/binary-${os_cpu_alt_name}/Packages | \
    gzip -9 >${this_repo_dir}/dists/${os_codename}/non-free/binary-${os_cpu_alt_name}/Packages.gz

  apt-ftparchive contents pool/main | \
    tee ${this_repo_dir}/dists/${os_codename}/main/Contents-${os_cpu_alt_name} | \
    gzip -9 >${this_repo_dir}/dists/${os_codename}/main/Contents-${os_cpu_alt_name}.gz
  apt-ftparchive contents pool/contrib | \
    tee ${this_repo_dir}/dists/${os_codename}/contrib/Contents-${os_cpu_alt_name} | \
    gzip -9 >${this_repo_dir}/dists/${os_codename}/contrib/Contents-${os_cpu_alt_name}.gz
  apt-ftparchive contents pool/non-free | \
    tee ${this_repo_dir}/dists/${os_codename}/non-free/Contents-${os_cpu_alt_name} | \
    gzip -9 >${this_repo_dir}/dists/${os_codename}/non-free/Contents-${os_cpu_alt_name}.gz

  apt-ftparchive release dists/${os_codename}/main/binary-${os_cpu_alt_name}/ \
    > ${this_repo_dir}/dists/${os_codename}/main/binary-${os_cpu_alt_name}/Release
  apt-ftparchive release dists/${os_codename}/contrib/binary-${os_cpu_alt_name}/ \
    > ${this_repo_dir}/dists/${os_codename}/contrib/binary-${os_cpu_alt_name}/Release
  apt-ftparchive release dists/${os_codename}/non-free/binary-${os_cpu_alt_name}/ \
    > ${this_repo_dir}/dists/${os_codename}/non-free/binary-${os_cpu_alt_name}/Release

  apt-ftparchive -c ${script_dir}/apt.conf release dists/${os_codename} \
    >${this_repo_dir}/dists/${os_codename}/Release

  # There's a good chance that, while we were off building, our GPG session
  #  expired.  There's also a good chance that the human that kicked off the
  #  process is not sitting waiting for the GPG prompt.  The GPG prompt would
  #  normally timeout, resulting in the entire process being wasted.  To prevent
  #  this, the first GPG process after having completd the build will be run
  #  repeatedly in a loop until it's successful (or the user hits CTRL+c a few
  #  times).

  gpg --pinentry-mode $gpg_pin_entry -a --yes --output ${this_repo_dir}/dists/${os_codename}/Release.gpg --local-user "${gpg_signing_uid}" --detach-sign ${this_repo_dir}/dists/${os_codename}/Release ||\
    warn "Repository signing failed.  Please run 'ikfs-repo-ubuntu-sign' manually to sign the repository files."

  gpg --pinentry-mode $gpg_pin_entry -a --yes --clearsign --output ${this_repo_dir}/dists/${os_codename}/InRelease --local-user "${gpg_signing_uid}" --detach-sign ${this_repo_dir}/dists/${os_codename}/Release ||\
    warn "Repository signing failed.  Please run 'ikfs-repo-ubuntu-sign' manually to sign the repository files."

  gpg --pinentry-mode $gpg_pin_entry --export "${gpg_signing_uid}" >${this_repo_dir}/signing_key.gpg ||\
    warn "Repository signing failed.  Please run 'ikfs-repo-ubuntu-sign' manually to sign the repository files."

  cd "${opwd}"
}
